#!/usr/bin/env bash

_ssh_clean_deps_ubuntu() {
    sudo apt-get -y remove ssh
}

_ssh_install_deps_ubuntu() {
    sudo apt-get -qq -y install ssh
}

_ssh_install_deps_arch() {
    sudo pacman -S --noconfirm --needed openssh
}

_ssh_link_files_arch() {
    ln -sf "${package_dir}/ssh-agent.service" "${HOME}/.config/systemd/user/ssh-agent.service"
    systemctl enable --user ssh-agent.service
}

_ssh_clean_files_arch() {
    systemctl disable --user ssh-agent.service
    rm "${HOME}/.config/ssh-agent.service"
}

_ssh_clean_deps_arch() {
    sudo pacman -Rs --noconfirm openssh
}

_ssh_pre_install() {
    mkdir -p "${HOME}/.ssh"
}

_ssh_install_deps() {
    :;
}

_ssh_link_files() {
    :;
}

_ssh_clean_files() {
    :;
}

_ssh_clean_deps() {
    :;
}

_ssh_post_clean() {
    rm -rf "${HOME}/.ssh"
}
