#!/usr/bin/env bash

_linux_init_install_deps_ubuntu() {
   sudo apt-get -y install \
      xdg-user-dirs \
      rsync \
      zip \
      unzip \
      ripgrep \
      wget
}

_linux_init_clean_deps_ubuntu() {
   sudo apt-get -y remove \
      xdg-user-dirs \
      rsync \
      zip \
      unzip \
      riprep \
      wget
}

_linux_init_install_deps_arch() {
   sudo pacman -S --needed --noconfirm \
      xdg-user-dirs \
      rsync \
      ripgrep
}

_linux_init_clean_deps_arch() {
   sudo pacman -Rs --noconfirm \
      xdg-user-dirs \
      rsync \
      ripgrep

}

_linux_init_pre_install() {
   mkdir -p "${HOME}/.config"
   mkdir -p "${HOME}/.config/systemd/user"
   mkdir -p "${data_dir}/Cache"
   mkdir -p "${data_dir}/Desktop"
   mkdir -p "${data_dir}/Documents"
   mkdir -p "${data_dir}/Music"
   mkdir -p "${data_dir}/Pictures"
   mkdir -p "${data_dir}/Public"
   mkdir -p "${data_dir}/Templates"
   mkdir -p "${data_dir}/Videos"

   migrate_dir "${HOME}/Cache" "${data_dir}/Cache"
   migrate_dir "${HOME}/Desktop" "${data_dir}/Desktop"
   migrate_dir "${HOME}/Documents" "${data_dir}/Documents"
   migrate_dir "${HOME}/Music" "${data_dir}/Music"
   migrate_dir "${HOME}/Pictures" "${data_dir}/Pictures"
   migrate_dir "${HOME}/Public" "${data_dir}/Public"
   migrate_dir "${HOME}/Templates" "${data_dir}/Templates"
   migrate_dir "${HOME}/Videos" "${data_dir}/Videos"

   ln -sF "${data_dir}/Cache" "${HOME}/Cache"
   ln -sF "${data_dir}/Desktop" "${HOME}/Desktop"
   ln -sF "${data_dir}/Documents" "${HOME}/Documents"
   ln -sF "${data_dir}/Music" "${HOME}/Music"
   ln -sF "${data_dir}/Pictures" "${HOME}/Pictures"
   ln -sF "${data_dir}/Public" "${HOME}/Public"
   ln -sF "${data_dir}/Templates" "${HOME}/Templates"
   ln -sF "${data_dir}/Videos" "${HOME}/Videos"
}

_linux_init_install_deps() {
   :
}

_linux_init_clean_deps() {
   :
}

_linux_init_link_files() {
   ln -sf "${package_dir}/user-dirs.dirs" "${HOME}/.config/user-dirs.dirs"
   ln -sf "${package_dir}/user-dirs.locale" "${HOME}/.config/user-dirs.locale"
}

_linux_init_clean_files() {
   rm "${HOME}/.config/user-dirs.dirs"
   rm "${HOME}/.config/user-dirs.locale"
}

_linux_init_post_clean() {
   rm "${HOME}/Cache"
   rm "${HOME}/Desktop"
   rm "${HOME}/Documents"
   rm "${HOME}/Music"
   rm "${HOME}/Pictures"
   rm "${HOME}/Public"
   rm "${HOME}/Templates"
   rm "${HOME}/Videos"
   rm -rf "${data_dir}/Cache"
   rm -rf "${data_dir}/Desktop"
   rm -rf "${data_dir}/Documents"
   rm -rf "${data_dir}/Music"
   rm -rf "${data_dir}/Pictures"
   rm -rf "${data_dir}/Public"
   rm -rf "${data_dir}/Templates"
   rm -rf "${data_dir}/Videos"
   rm -rf "${HOME}/.config"
}
