#!/usr/bin/env bash

_shell_link_files_linux() {
    ln -sf "${package_dir}/exports.sh" "${HOME}/.exports"
    ln -sf "${package_dir}/linux-aliases.sh" "${HOME}/.aliases"
    ln -sf "${package_dir}/git-prompt.sh" "${HOME}/.git-prompt.sh"
}

_shell_clean_files_linux() {
    rm "${HOME}/.exports"
    rm "${HOME}/.aliases"
    rm "${HOME}/.git-prompt.sh"
}

_shell_install_deps_ubuntu() {
    sudo apt-get -y install xclip
}

_shell_link_files_ubuntu() {
    _shell_link_files_linux
}

_shell_clean_files_ubuntu() {
    _shell_clean_files_linux
}

_shell_clean_deps_ubuntu() {
    sudo apt-get -y remove xclip
}

_shell_install_deps_arch() {
    sudo pacman -S --needed --noconfirm xclip
}

_shell_link_files_arch() {
    _shell_link_files_linux
}

_shell_clean_files_arch() {
    _shell_clean_files_linux
}

_shell_clean_deps_arch() {
    sudo pacman -Rs --noconfim xclip
}

_shell_link_files_macos() {
    ln -sf "${package_dir}/exports.sh" "${HOME}/.exports"
    ln -sf "${package_dir}/git-prompt.sh" "${HOME}/.git-prompt.sh"
}

_shell_clean_files_macos() {
    rm "${HOME}/.exports"
    rm "${HOME}/.git-prompt.sh"
}

_shell_pre_install() {
    mkdir -p "${HOME}/.local/bin"
}

_shell_install_deps() {
    :;
}

_shell_clean_deps() {
    :;
}

_shell_post_clean() {
    rm -rf "${HOME}/.local/bin"
}
