#!usr/bin/env bash

_git_install_deps_ubuntu() {
    sudo apt-get -y install git
}

_git_clean_deps_ubuntu() {
    sudo apt-get -y remove git
}

_git_install_deps_arch() {
    sudo pacman -S --noconfirm --needed git
}

_git_clean_deps_arch() {
    sudo pacman -Rs --noconfirm git
}

_git_install_deps_macos() {
    brew install git
}

_git_clean_deps_macos() {
    brew uninstall git
}

_git_pre_install() {
    mkdir -p "${HOME}/VersionControlledDocuments"
}

_git_link_files() {
    ln -sf "${package_dir}/global_gitignore" "${HOME}/.global_gitignore"
}

_git_post_install() {
  git config --global core.exclusedfile "~/.global_gitignore"
  git config --global core.pager "delta"

  git config --global user.name "Daniel Grumberg"
  git config --global user.email "dany.grumberg@gmail.com"

  git config --global pull.rebase "true"

  git config --global merge.conflictstyle "diff3"

  git config --global diff.colorMoved "default"

  git config --global delta.navigate "true"
}

_git_pre_clean() {
  rm -rf ~/.gitconfig
}

_git_clean_files() {
    rm "${HOME}/.global_gitignore"
}

_git_post_clean() {
    rm -rf "${HOME}/VersionsControlledDocuments"
}
