#!/usr/bin/env bash

_i3_wm_install_deps_arch() {
    sudo pacman -S --needed --noconfirm \
         i3-wm                          \
         i3blocks                       \
         i3lock                         \
         i3status
}

_i3_wm_link_files_arch() {
    ln -sf "${package_dir}/config-i3" "${HOME}/.config/i3"
    ln -sf "${package_dir}/config-i3status" "${HOME}/.config/i3status"
    ln -sf "${package_dir}/i3exit" "${HOME}/.local/bin"
}

_i3_wm_clean_files_arch() {
    rm "${HOME}/.config/i3"
    rm "${HOME}/.config/i3status"
    rm "${HOME}/.local/bin"
}

_i3_wm_clean_deps_arch() {
    sudo pacman -Rs --noconfirm \
         i3-wm                  \
         i3blocks               \
         i3lock                 \
         i3status
}

_i3_wm_install_deps() {
    :;
}

_i3_wm_clean_deps() {
    :;
}

_i3_wm_link_files() {
    :;
}

_i3_wm_clean_files() {
    :;
}
