#!/usr/bin/env bash

_xorg_install_deps_arch() {
    sudo pacman -S --needed --noconfirm \
        xorg                            \
        xorg-xrdb                       \
        fehbg                           \
        numlockx                        \
        rxvt-unicode
    pushd "${data_dir}/AURPackages"
    auracle clone urxvt-resize-font-git
    cd "urxvt-resize-font-git"
    makepkg -si --needed --noconfirm
    popd
}

_xorg_link_files_arch() {
    ln -sF "${package_dir}/xinitrc" "${HOME}/.xinitrc"
    ln -sF "${package_dir}/Xmodmap" "${HOME}/.Xmodmap"
    ln -sF "${package_dir}/Xresources" "${HOME}/.Xresources"
    ln -sF "${package_dir}/Xresources.d" "${HOME}/.Xresources.d"
    case "$(xdpyinfo | awk '/dimensions/ {print $2}')" in
        2560x1080)
            ln -sF "${package_dir}/Wallpapers/WidescreenWallpaper.png" "${HOME}/Pictures/Wallpaper.png"
            ;;
        *)
            ;;
    esac
    ln -sF "${package_dir}/fehbg" "${HOME}/.fehbg"
}

_xorg_clean_files_arch() {
    rm "${HOME}/.xinitrc"
    rm "${HOME}/.Xmodmap"
    rm "${HOME}/.Xresources"
    rm "${HOME}/.Xresources.d"
    rm "${HOME}/Pictures/Wallpaper.png"
    rm "${HOME}/.fehbg"
}

_xorg_clean_deps_arch() {
    sudo pacman -Rs --noconfirm \
        xorg                    \
        xorg-xrdb               \
        fehbg                   \
        numlockx                \
        rxvt-unicode            \
        urxvt-resize-font-git

    rm -rf "${data_dir}/AURPackages/urxvt-resize-font-git"
}

_xorg_install_deps() {
    :;
}

_xorg_clean_deps() {
    :;
}

_xorg_link_files() {
    :;
}

_xorg_clean_files() {
    :;
}
