#!/usr/bin/env bash

tmux_config_dir="${HOME}/.config/tmux"
tmux_plugin_dir="${tmux_config_dir}/plugins"

_tmux_pre_install() {
  mkdir -p "$tmux_config_dir"
  mkdir -p "$tmux_plugin_dir"
  local _tpm_dir="${tmux_plugin_dir}/tpm"
  if [[ ! -d "$_tpm_dir" ]]; then
    git clone 'https://github.com/tmux-plugins/tpm' "$_tpm_dir"
  fi
}

_tmux_install_deps() {
  :;
}

_tmux_install_deps_macos() {
  brew install tmux
}

_tmux_link_files() {
  :;
}

_tmux_link_files_macos() {
  tmux -f /dev/null -L temp start-server \; list-keys > "${tmux_config_dir}/reset.conf"
  link_file "${package_dir}/tmux_copy_command_macos.sh" "$utilities_dir"
  link_file "${package_dir}/tmux.conf" "$tmux_config_dir"
  link_file "${package_dir}/lt.fish" "${HOME}/.local/share/fish/functions/"
  link_file "${package_dir}/t.fish" "${HOME}/.local/share/fish/functions/"
}

_tmux_clean_files() {
  rm "${utilities_dir}/tmux_copy_command"
}

_tmux_clean_deps() {
  :;
}

_tmux_clean_deps_macos() {
  brew uninstall tmux
}

_tmux_post_clean() {
  rm -rf "$tmux_plugin_dir" || true
  rm -rf "$tmux_config_dir" || true
}

