#!/usr/bin/env bash

_emacs_install_doom() {
    git clone --depth 1 "https://github.com/hlissner/doom-emacs" "${HOME}/.emacs.d"
}

_emacs_install_deps_ubuntu() {
    sudo apt-get -y install emacs
    _emacs_install_doom
}

_emacs_clean_deps_ubuntu() {
    sudo apt-get -y remove emacs
}

_emacs_install_deps_arch() {
    sudo pacman -S --noconfirm --needed emacs
    _emacs_install_doom
}

_emacs_clean_deps_arch() {
    sudo pacman -Rs --noconfirm emacs
    rm -rf "${HOME}/.emacs.d"
}

_emacs_install_deps_macos() {
    # Ripgrep is a required dependency but fd isn't. Git is also a required
    # dependency but is needed much earlier than that...
    brew install ripgrep \
                 fd
    brew tap railwaycat/emacsmacport
    brew install emacs-mac --with-modules
    ln -s /usr/local/opt/emacs-mac/Emacs.app /Applications/Emacs.app
    _emacs_install_doom
}

_emacs_clean_files_macos() {
    rm -rf "${HOME}/.emacs.d"
    rm /Applications/Emacs.app
}

_emacs_clean_deps_macos() {
    brew uninstall emacs-mac
}

_emacs_pre_install() {
    mkdir -p "${HOME}/.emacs.d"
}

_emacs_link_files() {
    ln -sf "${package_dir}/doom.d" "${HOME}/.doom.d"
}

_emacs_post_install() {
    yes | "${HOME}/.emacs.d/bin/doom" install --no-config
    "${HOME}/.emacs.d/bin/doom" build
    "${HOME}/.emacs.d/bin/doom" sync
}

_emacs_clean_files() {
    rm "${HOME}/.doom.d"
}


