#!/usr/bin/env bash

_redshift_install_deps_arch() {
    sudo pacman -S --needed --noconfirm redshift
}

_redshift_link_files_arch() {
    ln -sF "${package_dir}/config-redshift" "${HOME}/.config/redshift"
}

_redshift_clean_files_arch() {
    rm "${HOME}/.config/redshift"
}

_redshift_clean_deps_arch() {
    sudo pacman -Rs --noconfirm redshift
}

_redshift_install_deps() {
    :;
}

_redshift_clean_deps() {
    :;
}

_redshift_link_files() {
    :;
}

_redshift_clean_files() {
    :;
}
