#!/usr/bin/env bash

_bash_install_deps_macos() {
    brew install bash
}

_bash_install_deps() { :; }

_bash_clean_deps_macos() {
    brew uninstall bash
}

_bash_clean_deps() { :; }

_bash_link_files_common() {
    ln -sf "${package_dir}/bashrc_common.sh" "${HOME}/.bashrc_common"
}

_bash_link_files_ubuntu() {
    _bash_link_files_common
    ln -sf "${package_dir}/bashrc_linux.sh" "${HOME}/.bashrc"
}

_bash_link_files_arch() {
    _bash_link_files_common
    ln -sf "${package_dir}/bashrc_linux.sh" "${HOME}/.bashrc"
    ln -sf "${package_dir}/bash_profile_arch.sh" "${HOME}/.bash_profile"
}

_bash_link_files_macos() {
    _bash_link_files_common
    ln -sf "${package_dir}/bashrc_macos.sh" "${HOME}/.bashrc"
}

_bash_clean_files_common() {
    rm "${HOME}/.bashrc_common"
}

_bash_clean_files_ubuntu() {
    _bash_clean_files_common
    rm "${HOME}/.bashrc"
}

_bash_clean_files_arch() {
    _bash_clean_files_common
    rm "${HOME}/.bashrc"
    rm "${HOME}/.bash_profile"
}

_bash_clean_files_macos() {
    _bash_clean_files_common
    rm "${HOME}/.bashrc"
}
