name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

  # Triggers workflow on Mondays at 3am
  schedule:
    - cron: '0 3 * * MON'

jobs:
  linux-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host: ['ubuntu', 'arch']

    steps:
      # This is a fix for random "Error: The operation was canceled"
      - name: Make some room in the instance
        run: |
          sudo rm -rf "/usr/share/dotnet" || true
          sudo rm -rf "/opt/ghc" || true
          sudo rm -rf "/usr/local/share/boost" || true
          sudo rm -rf "$AGENT_TOOLSDIRECTORY" || true
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          push: false
          context: .
          file: ./Dockerfile.${{ matrix.host }}
          load: true
          tags: dotfiles-${{ matrix.host }}:latest


